In [1]:
import cv2

In [5]:
im_g=cv2.imread("smallgray.png",0) #0 means read image in greyscale
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
im_g=cv2.imread("smallgray.png",1) #1 means read image in RBG
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [8]:
cv2.imwrite("new_smallgrey.png",im_g)


True

In [9]:
#Remembering list slicing
list_ex=[1,2,3,4,5,6]

In [11]:
list_ex[0:2]

[1, 2]

In [17]:
list_ex[2:5]

[3, 4, 5]

In [ ]:
#Applying slicing for arrays

In [19]:
array_ex=cv2.imread("smallgray.png",0)
array_ex

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [20]:
array_ex[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [21]:
array_ex[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [22]:
array_ex.shape

(3, 5)

In [23]:
array_ex[:,2:4]


array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [24]:
array_ex[1,3] #get single item

255

In [29]:
#Iterating through numpy array
array_ex

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
for i in array_ex:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [30]:
#Iterate through columns

In [31]:
for i in array_ex.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [32]:
for i in array_ex.flat: #Iterate one element
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [34]:
#Stock numpy arrays
import numpy
new_array=numpy.hstack(array_ex, array_ex.T)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [42]:
#hstack takes one positional argument, so we will use a tupple where we store the two arrays, and the tupple will be the single argument for the hstack function
new_array=numpy.hstack((array_ex, array_ex)) #horizontal stack. all the input array dimensions for the concatenation axis must match exactly
new_array

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [39]:
new_array_2=numpy.hstack((array_ex,array_ex,new_array))
new_array_2

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [40]:
print(new_array_2)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143 187 158 104
  121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147 198 125 255
  255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182 209 134 255
   97 182]]


In [45]:
new_array_3=numpy.vstack((array_ex,array_ex,array_ex))#vertical stack
new_array_3

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [50]:
#Spliting arrays
new_list=numpy.hsplit(new_array_3,5)
new_list

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [47]:
print(new_list[0])

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [52]:
new_list_2=numpy.vsplit(new_array_2,3)
new_list_2

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
         121, 143, 187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
         255, 147, 198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
          97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]